import React, { useState } from 'react';
import { BarChart, Bar, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

const AdminDashboard = () => {
  const [activeTab, setActiveTab] = useState('overview');
  const stats = { users: 1250, active: 890, premium: 340, trades: 15420, volume: 250000000, revenue: 8500000 };
  const revenueData = [{ month: 'Jan', revenue: 850000 }, { month: 'Feb', revenue: 920000 }, { month: 'Mar', revenue: 1100000 }, { month: 'Apr', revenue: 1250000 }, { month: 'May', revenue: 1400000 }, { month: 'Jun', revenue: 1580000 }];
  const users = [{ id: 1, name: 'John Doe', email: 'john@example.com', plan: 'premium', status: 'active' }, { id: 2, name: 'Jane Smith', email: 'jane@example.com', plan: 'pro', status: 'active' }, { id: 3, name: 'Mike Johnson', email: 'mike@example.com', plan: 'free', status: 'inactive' }];
  return <div className="admin-dashboard"><div className="page-header"><h1>Admin Dashboard</h1><p>Monitor users, trading activity, and subscription revenue.</p></div><div className="stats-grid">{Object.entries(stats).map(([key, value]) => <div className="stat-card" key={key}><div className="stat-content"><span className="stat-label">{key}</span><span className="stat-value">{typeof value === 'number' ? value.toLocaleString() : value}</span></div></div>)}</div><div className="admin-tabs">{['overview','users','settings'].map((tab) => <button key={tab} className={`tab-btn ${activeTab === tab ? 'active' : ''}`} onClick={() => setActiveTab(tab)}>{tab}</button>)}</div>{activeTab === 'overview' && <div className="card"><h3>Revenue overview</h3><ResponsiveContainer width="100%" height={320}><BarChart data={revenueData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" /><YAxis /><Tooltip /><Legend /><Bar dataKey="revenue" name="Revenue (NGN)" /></BarChart></ResponsiveContainer></div>}{activeTab === 'users' && <div className="card"><h3>User management</h3><div className="table-responsive"><table className="table"><thead><tr><th>Name</th><th>Email</th><th>Plan</th><th>Status</th></tr></thead><tbody>{users.map((u) => <tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td><span className={`badge ${u.plan}`}>{u.plan}</span></td><td>{u.status}</td></tr>)}</tbody></table></div></div>}{activeTab === 'settings' && <div className="card"><h3>Platform settings</h3><p>Administrative controls can be connected to backend configuration endpoints here.</p></div>}</div>;
};
export default AdminDashboard;
