import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
const Register = () => {
  const [form, setForm] = useState({ firstName:'', lastName:'', email:'', phone:'', password:'' }); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const { register }=useAuth(); const navigate=useNavigate();
  const change=(e)=>setForm({...form,[e.target.name]:e.target.value});
  const submit=async(e)=>{e.preventDefault();setBusy(true);setError('');try{await register(form);navigate('/dashboard');}catch(err){setError(err.response?.data?.message||err.message||'Registration failed');}finally{setBusy(false);}};
  return <div className="auth-container"><div className="auth-card"><div className="auth-header"><h1>Create account</h1><p>Start your trading workspace.</p></div>{error&&<div className="alert alert-error">{error}</div>}<form className="auth-form" onSubmit={submit}><div className="form-row"><div className="form-group"><label>First name</label><input className="form-control" name="firstName" value={form.firstName} onChange={change} required /></div><div className="form-group"><label>Last name</label><input className="form-control" name="lastName" value={form.lastName} onChange={change} required /></div></div><div className="form-group"><label>Email</label><input className="form-control" type="email" name="email" value={form.email} onChange={change} required /></div><div className="form-group"><label>Phone</label><input className="form-control" name="phone" value={form.phone} onChange={change} /></div><div className="form-group"><label>Password</label><input className="form-control" type="password" name="password" minLength="6" value={form.password} onChange={change} required /></div><button className="btn btn-primary btn-block" disabled={busy}>{busy?'Creating…':'Create account'}</button></form><div className="auth-footer">Already registered? <Link to="/login">Sign in</Link></div></div></div>;
};
export default Register;
